### ISSUE TITLE
module 'bb.data' has no attribute 'getVar'

### ISSUE THREAD

**Issue by Ole2mail** [Angstrom-distribution/angstrom-manifest#36]
```ole2@ole2-ThinkPad-P50:~/Projects/angstrom$ MACHINE=qemux86-64 bitbake console-image
ERROR: Unable to start bitbake server
ERROR: Last 10 lines of server log for this session (/home/ole2/Projects/angstrom/bitbake-cookerdaemon.log):
  File "/home/ole2/Projects/angstrom/bitbake/lib/bb/data_smart.py", line 436, in DataSmart.expand(s='${@bb.utils.contains("TUNE_FEATURES", "m32", "x86:", "" ,d)}qemuall:${MACHINE}:${@bb.data.getVar(\'FEED_ARCH\', d,1).replace(\'all\',\'noarch\')}', varname='MACHINEOVERRIDES'):
         def expand(self, s, varname = None):
    >        return self.expandWithRefs(s, varname).value
     
  File "/home/ole2/Projects/angstrom/bitbake/lib/bb/data_smart.py", line 426, in DataSmart.expandWithRefs(s='${@bb.utils.contains("TUNE_FEATURES", "m32", "x86:", "" ,d)}qemuall:qemux86-64:${@bb.data.getVar(\'FEED_ARCH\', d,1).replace(\'all\',\'noarch\')}', varname='MACHINEOVERRIDES'):
                 except Exception as exc:
    >                raise ExpansionError(varname, s, exc) from exc
     
bb.data_smart.ExpansionError: Failure expanding variable MACHINEOVERRIDES, expression was ${@bb.utils.contains("TUNE_FEATURES", "m32", "x86:", "" ,d)}qemuall:qemux86-64:${@bb.data.getVar('FEED_ARCH', d,1).replace('all','noarch')} which triggered exception AttributeError: module 'bb.data' has no attribute 'getVar'
```
```
ole2@ole2-ThinkPad-P50:~/Projects/angstrom$ uname -a
Linux ole2-ThinkPad-P50 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
ole2@ole2-ThinkPad-P50:~/Projects/angstrom$ which bitbake
/home/ole2/Projects/angstrom/bitbake/bin/bitbake

ole2@ole2-ThinkPad-P50:~/Projects/angstrom$ bitbake --version
BitBake Build Tool Core version 1.36.0
```
```
ole2@ole2-ThinkPad-P50:~/Projects/angstrom$ ../bin/repo --version
repo version v1.12.37
       (from https://gerrit.googlesource.com/git-repo)
repo launcher version 1.23
       (from /home/ole2/Projects/bin/repo)
git version 2.7.4
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609]
```
```
ole2@ole2-ThinkPad-P50:~/Projects/angstrom$ ../bin/repo init -u git@github.com:Angstrom-distribution/angstrom-manifest.git -b angstrom-v2017.12-rocko
```
trying to build Angstrom based on revision="angstrom-v2017.12-rocko"
but the similar failure is happening with revision="angstrom-v2017.06-yocto2.3"

```
ole2@ole2-ThinkPad-P50:~/Projects/angstrom$ MACHINE=qemux86-64 bitbake console-image
ERROR: Unable to parse MACHINEOVERRIDES
Traceback (most recent call last):
  File "/home/ole2/Projects/angstrom/bitbake/lib/bb/data_smart.py", line 412, in DataSmart.expandWithRefs(s='${TARGET_OS}:${TRANSLATED_TARGET_ARCH}:build-${BUILD_OS}:pn-${PN}:${MACHINEOVERRIDES}:${DISTROOVERRIDES}:${CLASSOVERRIDE}:forcevariable', varname='OVERRIDES'):
                 try:
    >                s = __expand_var_regexp__.sub(varparse.var_sub, s)
                     try:
  File "/home/ole2/Projects/angstrom/bitbake/lib/bb/data_smart.py", line 111, in VariableParse.var_sub(match=<_sre.SRE_Match object; span=(66, 85), match='${MACHINEOVERRIDES}'>):
                 else:
    >                var = self.d.getVarFlag(key, "_content")
                 self.references.add(key)
  File "/home/ole2/Projects/angstrom/bitbake/lib/bb/data_smart.py", line 794, in DataSmart.getVarFlag(var='MACHINEOVERRIDES', flag='_content', expand=True, noweakdefault=False, parsing=False):
                     cachename = var + "[" + flag + "]"
    >            value = self.expand(value, cachename)
     
  File "/home/ole2/Projects/angstrom/bitbake/lib/bb/data_smart.py", line 436, in DataSmart.expand(s='${@bb.utils.contains("TUNE_FEATURES", "m32", "x86:", "" ,d)}qemuall:${MACHINE}:${@bb.data.getVar(\'FEED_ARCH\', d,1).replace(\'all\',\'noarch\')}', varname='MACHINEOVERRIDES'):
         def expand(self, s, varname = None):
    >        return self.expandWithRefs(s, varname).value
     
  File "/home/ole2/Projects/angstrom/bitbake/lib/bb/data_smart.py", line 426, in DataSmart.expandWithRefs(s='${@bb.utils.contains("TUNE_FEATURES", "m32", "x86:", "" ,d)}qemuall:qemux86-64:${@bb.data.getVar(\'FEED_ARCH\', d,1).replace(\'all\',\'noarch\')}', varname='MACHINEOVERRIDES'):
                 except Exception as exc:
    >                raise ExpansionError(varname, s, exc) from exc
     
bb.data_smart.ExpansionError: Failure expanding variable MACHINEOVERRIDES, expression was ${@bb.utils.contains("TUNE_FEATURES", "m32", "x86:", "" ,d)}qemuall:qemux86-64:${@bb.data.getVar('FEED_ARCH', d,1).replace('all','noarch')} which triggered exception AttributeError: module 'bb.data' has no attribute 'getVar'
```
but the similar failure is happening with revision="angstrom-v2016.12-yocto2.2"

```
ole2@ole2-ThinkPad-P50:~/Projects/angstrom$ MACHINE=qemux86-64 bitbake console-image
ERROR: Unable to parse /home/ole2/Projects/angstrom/bitbake/lib/bb/data_smart.py
Traceback (most recent call last):
  File "/home/ole2/Projects/angstrom/bitbake/lib/bb/data_smart.py", line 400, in DataSmart.expandWithRefs(s="${@bb.parse.BBHandler.vars_from_file(d.getVar('FILE'),d)[0] or 'defaultpkgname'}", varname='PN'):
                 except Exception as exc:
    >                raise ExpansionError(varname, s, exc) from exc
     
bb.data_smart.ExpansionError: Failure expanding variable PN, expression was ${@bb.parse.BBHandler.vars_from_file(d.getVar('FILE'),d)[0] or 'defaultpkgname'} which triggered exception TypeError: getVar() missing 1 required positional argument: 'expand'
```
unfortunately unable to verify if similar failure is happening with revision="angstrom-v2016.06-yocto2.1"
Fetching projects:  97% (37/38)  fatal: Couldn't find remote ref refs/heads/master
error: Cannot fetch linux4sam/meta-atmel

**Comment by koenkooi** [comment]
It looks like there's some contamination in your build environment, can you make sure you start with a clean shell?

There shouldn't be any bb.data.getVar calls related the FEED_ARCH in v2017.12:

```
[koen@fedora-vm v2017.12]$ repo grep bb.data.getVar
bitbake/lib/bb/cache.py:    bb_data.setVar('TMPDIR', bb_data.getVar('TMPDIR') or "")
bitbake/lib/bb/cache.py:    if not bb_data.getVar('TOPDIR', False):
layers/meta-edison/recipes-kernel/linux/linux.inc:    devicetree = bb.data.getVar('KERNEL_DEVICETREE', d, 1) or ''
layers/meta-edison/recipes-kernel/linux/linux.inc:      depends = bb.data.getVar("DEPENDS", d, 1)
```

This is what I get locally with a few checkout:
```
[koen@fedora-vm v2017.12]$ MACHINE=qemux86-64 bitbake console-image
NOTE: Started PRServer with DBfile: /build/angstrom/v2017.12/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 43989, PID: 28757
Loading cache: 100% |##########################################################################################################################################################################################################| Time: 0:00:01
Loaded 4878 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################################################################################################################| Time: 0:00:45
Parsing of 3837 .bb files complete (3831 cached, 6 parsed). 4884 targets, 465 skipped, 0 masked, 0 errors.
WARNING: No recipes available for:
  /build/angstrom/v2017.12/layers/meta-freescale/dynamic-layers/browser-layer/recipes-browser/chromium/chromium-wayland_48.0.2548.0.bbappend
  /build/angstrom/v2017.12/layers/meta-freescale/dynamic-layers/browser-layer/recipes-browser/chromium/chromium_52.0.2743.76.bbappend
  /build/angstrom/v2017.12/layers/meta-beagleboard/common-bsp/recipes-kernel/dtc/dtc_git.bbappend
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'connman-systemd' (but /build/angstrom/v2017.12/layers/meta-angstrom/recipes-images/angstrom/console-image.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'connman-systemd' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['connman-systemd']
ERROR: Required build target 'console-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['console-image', 'connman-systemd']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
```

What happens with ```MACHINE=qemux86-64 bitbake angstrom-image``` ? That should give the same sort of rootfs as console-image.

**Comment by Ole2mail** [comment]
confirmed: the issue has been related to the manual proposal to add bitbake/bin to the PATH. will work unless multiple build environments are in use simultaneously.
